import grpc
from concurrent import futures
from config import GRPC_SERVER_ADDRESS

# These files are generated by codegen.py from the .proto file.
# If they don't exist yet, run: python codegen.py
try:
    import product_pb2
    import product_pb2_grpc
except ImportError:
    print("[!] Run 'python codegen.py' first to generate the gRPC stubs.")
    raise

# In-memory product store
_db = {}
_next_id = 1


class ProductServicer(product_pb2_grpc.ProductServiceServicer):
    """Implementation of the ProductService defined in the .proto file."""

    def CreateProduct(self, request, context):
        global _next_id
        product = product_pb2.Product(
            id=_next_id,
            name=request.name,
            price=request.price,
            in_stock=True,
        )
        _db[_next_id] = product
        _next_id += 1
        print(f"[Server] Created product: {product.name} (id={product.id})")
        return product

    def GetProduct(self, request, context):
        if request.id not in _db:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details(f"Product {request.id} not found")
            return product_pb2.Product()
        return _db[request.id]

    def ListProducts(self, request, context):
        return product_pb2.ProductList(products=list(_db.values()))


def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    product_pb2_grpc.add_ProductServiceServicer_to_server(ProductServicer(), server)
    server.add_insecure_port(GRPC_SERVER_ADDRESS)
    print(f"[Server] gRPC server listening on {GRPC_SERVER_ADDRESS}")
    server.start()
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
